#!/bin/bash

#############################################
# まん2000 自動デプロイスクリプト
# 新しいコンテンツを自動的にGitにpushしてデプロイ
#############################################

set -e  # エラーで停止

# カラー出力
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# ロゴ表示
echo -e "${BLUE}"
echo "╔══════════════════════════════════════╗"
echo "║   まん2000 自動デプロイシステム      ║"
echo "╚══════════════════════════════════════╝"
echo -e "${NC}"

# site-config.jsonから設定を読み込み
CONFIG_FILE="site-config.json"

if [ ! -f "$CONFIG_FILE" ]; then
    echo -e "${RED}❌ エラー: site-config.json が見つかりません${NC}"
    exit 1
fi

# jqがインストールされているか確認
if ! command -v jq &> /dev/null; then
    echo -e "${YELLOW}⚠️ jqがインストールされていません。brew install jq を実行してください${NC}"
    AUTO_DEPLOY="true"
else
    AUTO_DEPLOY=$(jq -r '.repository.auto_deploy // true' "$CONFIG_FILE")
fi

if [ "$AUTO_DEPLOY" != "true" ]; then
    echo -e "${YELLOW}ℹ️ 自動デプロイが無効になっています${NC}"
    echo -e "${YELLOW}   site-config.json で auto_deploy を true に設定してください${NC}"
    exit 0
fi

# Step 1: メタデータ統合
echo -e "${BLUE}📊 Step 1: メタデータを統合中...${NC}"
node scripts/aggregate-metadata.js

if [ $? -ne 0 ]; then
    echo -e "${RED}❌ メタデータ統合に失敗しました${NC}"
    exit 1
fi

# Step 2: Git状態確認
echo -e "\n${BLUE}🔍 Step 2: Git状態を確認中...${NC}"

if [ ! -d ".git" ]; then
    echo -e "${YELLOW}⚠️ Gitリポジトリが初期化されていません${NC}"
    echo -e "${YELLOW}   以下のコマンドを実行してください:${NC}"
    echo -e "   ${GREEN}git init${NC}"
    echo -e "   ${GREEN}git remote add origin YOUR_REPO_URL${NC}"
    exit 1
fi

# リモートURLを確認
REMOTE_URL=$(git remote get-url origin 2>/dev/null || echo "")

if [ -z "$REMOTE_URL" ]; then
    echo -e "${YELLOW}⚠️ Gitリモートが設定されていません${NC}"
    echo -e "${YELLOW}   site-config.json の remote_url を確認してください${NC}"
    exit 1
fi

echo -e "${GREEN}✓ リモート: $REMOTE_URL${NC}"

# Step 3: 変更をステージング
echo -e "\n${BLUE}📦 Step 3: 変更をステージング中...${NC}"

git add .

# 変更があるか確認
if git diff --cached --quiet; then
    echo -e "${GREEN}✓ デプロイする新しい変更はありません${NC}"
    exit 0
fi

# 変更サマリーを表示
echo -e "${GREEN}変更されたファイル:${NC}"
git diff --cached --name-status | head -n 20

# Step 4: コミット
echo -e "\n${BLUE}💾 Step 4: コミット中...${NC}"

# 最新のテーマ情報を取得（コミットメッセージ用）
LATEST_THEME=$(find . -name "metadata.json" -type f -exec stat -f "%m %N" {} + 2>/dev/null | sort -rn | head -1 | cut -d' ' -f2- | xargs -I {} dirname {})

if [ -n "$LATEST_THEME" ]; then
    THEME_NAME=$(basename "$LATEST_THEME")
    BOOK_NAME=$(basename "$(dirname "$LATEST_THEME")")
    COMMIT_MSG="Add new content: $BOOK_NAME - $THEME_NAME

🤖 Generated with Claude Code
Generated by まん2000プロジェクト
Date: $(date '+%Y-%m-%d %H:%M:%S')"
else
    COMMIT_MSG="Update learning content

🤖 Generated with Claude Code
Generated by まん2000プロジェクト
Date: $(date '+%Y-%m-%d %H:%M:%S')"
fi

git commit -m "$COMMIT_MSG"

if [ $? -ne 0 ]; then
    echo -e "${RED}❌ コミットに失敗しました${NC}"
    exit 1
fi

echo -e "${GREEN}✓ コミット完了${NC}"

# Step 5: プッシュ
echo -e "\n${BLUE}🚀 Step 5: リモートにプッシュ中...${NC}"

BRANCH=$(git rev-parse --abbrev-ref HEAD)
echo -e "${BLUE}   ブランチ: $BRANCH${NC}"

git push origin "$BRANCH"

if [ $? -ne 0 ]; then
    echo -e "${RED}❌ プッシュに失敗しました${NC}"
    echo -e "${YELLOW}   初回プッシュの場合: git push -u origin $BRANCH${NC}"
    exit 1
fi

# Step 6: 完了
echo -e "\n${GREEN}╔══════════════════════════════════════╗${NC}"
echo -e "${GREEN}║     🎉 デプロイ完了！                ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════╝${NC}"

echo -e "\n${BLUE}📊 デプロイ情報:${NC}"
echo -e "   コミット: $(git rev-parse --short HEAD)"
echo -e "   ブランチ: $BRANCH"
echo -e "   リモート: $REMOTE_URL"
echo -e "\n${YELLOW}ℹ️ Netlify/Vercelで自動ビルドが開始されます（1-2分）${NC}"
echo -e "${YELLOW}   サイトURL: https://yoursite.com${NC}\n"
